AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket with Static Website Hosting Enabled

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket

Resources:
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${StaticWebsiteBucket.Arn}/*"

Outputs:
  WebsiteURL:
    Description: Static website URL
    Value: !GetAtt StaticWebsiteBucket.WebsiteURL

  BucketNameOutput:
    Description: The name of the created bucket
    Value: !Ref StaticWebsiteBucket
