AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket with Static Website Hosting (Secure & Audited)

Parameters:
  BucketName:
    Type: String
    Description: The name of the static website bucket

  LogsBucketName:
    Type: String
    Description: Bucket name for access logs

Resources:
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

      VersioningConfiguration:
        Status: Enabled

      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  StaticBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${StaticWebsiteBucket.Arn}/*"

Outputs:
  WebsiteURL:
    Description: Static website URL (HTTP-only by design)
    Value: !GetAtt StaticWebsiteBucket.WebsiteURL

  BucketNameOutput:
    Description: Website bucket name
    Value: !Ref StaticWebsiteBucket
